spring:
  application:
    name: eureka-client
eureka:
  client:
    statusPageUrlPath: ${server.servletPath}/info
    healthCheckUrlPath: ${server.servletPath}/health
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/, http://peer3:8763/eureka/
server:
  port: 10001