spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/, http://peer3:8763/eureka/
